#!/bin/sh
#
# Copyright (C) 2008 IAIK, Graz University of Technology
#

FULLPATH=`readlink -f $0`
DIR=`dirname ${FULLPATH}`  # the absolute directory this script is located in

LIBPATH=${DIR}/../lib
EXTLIBPATH=${DIR}/../ext_libs

JUNIT_LOCAL=${EXTLIBPATH}/junit.jar

CLASSPATH_LOCAL=${EXTLIBPATH}/activation.jar
CLASSPATH_LOCAL=${EXTLIBPATH}/axis-ant.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/axis.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/commons-daemon.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/commons-discovery-0.2.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/commons-logging-1.0.4.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/jaxrpc.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/log4j-1.2.8.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/mail.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/saaj.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/wsdl4j-1.5.1.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/xerces.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${EXTLIBPATH}/hsqldbmin.jar:${CLASSPATH_LOCAL}

CLASSPATH_LOCAL=${LIBPATH}/iaik_jtss_tcs.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${LIBPATH}/iaik_jtss_tcs_soap.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${LIBPATH}/iaik_jtss_tsp.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${LIBPATH}/iaik_jtss_tsp_soap.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${DIR}/iaik_jtss_tsp_tests.jar:${CLASSPATH_LOCAL}
CLASSPATH_LOCAL=${JUNIT_LOCAL}:${CLASSPATH_LOCAL}

java -cp ${CLASSPATH_LOCAL} iaik.tc.tss.test.tsp.java.simple.TestMain

